#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: mmistakes/minimal-mistakes@4.27.3 
#remote_theme: pages-themes/minimal
remote_theme: pages-themes/hacker
#remote_theme: pages-themes/slate

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

sass:
  style: compressed
