remote_theme: pages-themes/cayman
#remote_theme: pages-themes/minimal
#remote_theme: pages-themes/hacker
#remote_theme: pages-themes/slate
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


github:
  is_project_page: false
  show_description: false
